FROM python:3.9-slim

WORKDIR /app

# Copy master code
COPY master/master.py .
COPY master/requirements.txt .

# Copy data
COPY master/data/ data/

# Create results directory
RUN mkdir -p results

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run master
CMD ["python", "master.py"]
